version: 0.2

env:
  variables:
    CI: "true"
#   parameter-store:
#     key: "value"
#     key: "value"
            
phases:
  install:
    commands:
      - npm install yarn -g
  pre_build:
    commands:
      - yarn install
      - yarn test
  build:
    commands:
      - yarn build
artifacts:
  files:
    - '**/*'
  name: shanedg-dot-com-$(AWS_REGION)-$(date +%Y-%m-%d) 
  base-directory: build
cache:
  paths:
    - 'node_modules/**/*'
